<?php

declare(strict_types=1);

namespace Onelegstudios\Refit\Libraries\Flux;

/**
 * The recorded list of icons Flux renders from inside its own components.
 *
 * Scanning the installed package is always better — {@see FluxLibrary::internals()}
 * stays correct as Flux changes, and it sees the licensed `flux-pro` stubs on the
 * machines that have them. This list is what refit falls back to when there is
 * nothing to scan: a fixture, a project where Flux is not installed yet, or a
 * contributor checkout without a Pro licence.
 *
 * The manifest is generated by `bin/scan-flux-internals.php` and committed, so
 * the Pro names survive in a repository whose contributors mostly cannot produce
 * them. Icon *names* are facts about which artwork a component asks for; none of
 * Flux's own source is copied here.
 */
final class Internals
{
    /**
     * Where each Flux edition keeps the Blade stubs refit reads, relative to the
     * project root.
     *
     * `flux-pro` is a licensed package, so it is absent from most installs —
     * including every contributor checkout without a licence. Its absence is
     * ordinary, not an error.
     *
     * @var list<string>
     */
    public const array STUB_DIRECTORIES = [
        'vendor/livewire/flux/stubs',
        'vendor/livewire/flux-pro/stubs',
    ];

    /**
     * @var array<string, mixed>|null
     */
    private static ?array $manifest = null;

    public static function manifestPath(): string
    {
        return dirname(__DIR__, 3).'/resources/flux/internal-icons.json';
    }

    /**
     * Every recorded name, across both editions.
     *
     * @return list<string>
     */
    public static function names(): array
    {
        $names = [];

        foreach (self::editions() as $edition) {
            foreach ($edition['icons'] as $name) {
                $names[] = $name;
            }
        }

        $names = array_values(array_unique($names));

        sort($names);

        return $names;
    }

    /**
     * The names one edition contributes, for reporting which are Pro-only.
     *
     * @return list<string>
     */
    public static function namesFor(string $package): array
    {
        return self::editions()[$package]['icons'] ?? [];
    }

    /**
     * The recorded editions, keyed by Composer package name.
     *
     * @return array<string, array{version: ?string, scanned: bool, icons: list<string>}>
     */
    public static function editions(): array
    {
        $editions = self::manifest()['editions'] ?? null;

        if (! is_array($editions)) {
            return [];
        }

        $normalised = [];

        foreach ($editions as $package => $edition) {
            if (! is_string($package) || ! is_array($edition)) {
                continue;
            }

            $version = $edition['version'] ?? null;
            $icons = $edition['icons'] ?? [];

            $normalised[$package] = [
                'version' => is_string($version) ? $version : null,
                'scanned' => (bool) ($edition['scanned'] ?? false),
                'icons' => array_values(array_filter(
                    is_array($icons) ? $icons : [],
                    is_string(...),
                )),
            ];
        }

        return $normalised;
    }

    /**
     * @return array<string, mixed>
     */
    private static function manifest(): array
    {
        if (self::$manifest !== null) {
            return self::$manifest;
        }

        $path = self::manifestPath();

        if (! is_file($path)) {
            return self::$manifest = [];
        }

        $decoded = json_decode((string) file_get_contents($path), true);

        return self::$manifest = is_array($decoded) ? $decoded : [];
    }

    /**
     * Drop the cached manifest, so a test can write one and read it back.
     */
    public static function flush(): void
    {
        self::$manifest = null;
    }
}
